LOCAL_PATH := $(call my-dir)


include $(CLEAR_VARS)

$(info Serial result = $(TARGET_ARCH))

LOCAL_MODULE := python3.5m

LOCAL_C_INCLUDES := $(LOCAL_PATH)/include/$(TARGET_ARCH)

LOCAL_STATIC_LIBRARIES := 

LOCAL_SHARED_LIBRARIES :=

LOCAL_LDLIBS := -L$(SYSROOT)/usr/lib/$(TARGET_ARCH) -llog

LOCAL_SRC_FILES = lib/$(TARGET_ARCH)/libpython3.5m.so 

include $(PREBUILT_SHARED_LIBRARY)


include $(CLEAR_VARS)


LOCAL_MODULE := python3

LOCAL_C_INCLUDES := $(LOCAL_PATH)/include/$(TARGET_ARCH)

LOCAL_STATIC_LIBRARIES := 

LOCAL_SHARED_LIBRARIES := python3.5m

LOCAL_LDLIBS := -L$(SYSROOT)/usr/lib/$(TARGET_ARCH) -llog

LOCAL_SRC_FILES = lib/$(TARGET_ARCH)/libpython3.so 

include $(PREBUILT_SHARED_LIBRARY)



