LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := $(notdir $(LOCAL_PATH))

LOCAL_C_INCLUDES := $(LOCAL_PATH)/$(NDK_TOOLCHAIN_VERSION)/include

LOCAL_SRC_FILES := lib/$(TARGET_ARCH_ABI)/$(NDK_TOOLCHAIN_VERSION)/lib$(LOCAL_MODULE).so

include $(PREBUILT_SHARED_LIBRARY)

